### ISSUE TITLE
How do I launch the game?

### ISSUE THREAD

**Issue by Tim79000** [seanpm2001/MCPYE#11]
???

**Comment by seanpm2001** [comment]
I am sorry, the game is not functional yet. I don't have enough development time to work on it myself, and I don't have the volunteers. Also, sorry for the 2 and a half month late response, I didn't get the notification until recently.

I am closing this issue, as this is a common question that has already been asked. I have put in a system to try to bring this type of confusion down, as I have had poor documentation here until recently.

For now, you can try getting the official game, or you can try an open source version (the most developed alternative I know of is [minetest](https://github.com/minetest/))
