### ISSUE TITLE
Not able to start the Windows setup

### ISSUE THREAD

**Issue by Struow** [seanpm2001/MCPYE#2]
![c1763117b5ee68fba6944d2b3bcebfca](https://user-images.githubusercontent.com/61907178/83531908-3b2df880-a4f6-11ea-887b-b31c942cbca7.png)

**Comment by seanpm2001** [comment]
It is still in a very basic form. It is not ready yet. The EXE file is just there for when I get the game into a working state. The same goes for the other setup files. This game is still highly incomplete.

**Comment by seanpm2001** [comment]
I am closing this issue, but pinning it as an example, for people who don't read the commit info. There is so much of it (information and commit data) and people can be so eager to see the project.
